### ISSUE TITLE
Why cypher need 2 parameters in Java not 1

### ISSUE THREAD

**Issue by 631068264** [neo4j-contrib/neo4j-spark-connector#122]
want to read data and print it to console
version 
<maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <spark.version>2.3.2</spark.version>
        <scala.version>2.11.12</scala.version>
neo4j  3.5.14
neo4j-spark-connector  2.1.0-M4   I have try 2.4.0-M6 the same error

```java
import com.yizhisec.bigdata.model.Node;
import com.yizhisec.bigdata.utils.Config;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.catalyst.encoders.ExpressionEncoder;
import org.apache.spark.sql.streaming.StreamingQuery;
import org.apache.spark.sql.streaming.StreamingQueryException;
import org.apache.spark.sql.streaming.Trigger;
import org.neo4j.spark.Neo4j;

import java.io.IOException;
import java.util.HashMap;
import java.util.Properties;

public class Neo4jDemo {


    public static void main(String[] args) throws IOException, StreamingQueryException {

        String appName = "neo4j-demo";

        Properties prop = Config.getProp();
        SparkSession spark = SparkSession.builder()
                .appName(appName)
                .master("local[*]")
                .config("spark.neo4j.bolt.url", prop.getProperty("spark.neo4j.bolt.url"))
                .config("spark.neo4j.bolt.user", prop.getProperty("spark.neo4j.bolt.user"))
                .config("spark.neo4j.bolt.password", prop.getProperty("spark.neo4j.bolt.password"))
                .getOrCreate();

        Neo4j neo = new Neo4j(spark.sparkContext());
        HashMap<String, Object> params = new HashMap<>();
        Dataset<Row> ds = neo.cypher("MATCH (n:Node) RETURN n.name as name", ).loadDataFrame();
        Dataset<Node> dNode = ds.as(ExpressionEncoder.javaBean(Node.class));
        StreamingQuery query = dNode.writeStream().format("console")
                .start();

        query.awaitTermination();

    }
}

```

if use
```
Dataset<Row> ds = neo.cypher("MATCH (n:Node) RETURN n.name as name", null).loadDataFrame();
```

get
```
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.immutable.MapLike$class.$plus$plus(MapLike.scala:88)
	at scala.collection.immutable.AbstractMap.$plus$plus(Map.scala:194)
	at org.neo4j.spark.Neo4j.cypher(Neo4j.scala:167)
	at com.yizhisec.bigdata.Neo4jDemo.main(Neo4jDemo.java:35)
```

It can't use like  [the example](https://github.com/neo4j-contrib/neo4j-spark-connector#usage-examples)

What should I use in the second parameters ?

**Comment by jexp** [comment]
Just pass Map.empty there or leave it off, it uses default parameters  if you leave it off.
