### ISSUE TITLE
Add connection check before reading and writing

### ISSUE THREAD

**Issue by utnaf** [neo4j-contrib/neo4j-spark-connector#170]
When writing ad dataset to neo4j, if there is a driver misconfiguration we have this error:

```
org.apache.spark.SparkException: Writing job aborted.
  at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:92)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:260)
```

that doesn't say too much about why the writing failed. 
The actual error can be seen down the stack trace but I think it's easier to perform a connection test before trying to read or write data, this way we can show a better error message.

**Comment by moxious** [comment]
Related: https://github.com/neo4j-contrib/neo4j-spark-connector/issues/183

Core issue of surfacing underlying driver errors.  Maybe both are solveable at once?

**Comment by utnaf** [comment]
Running a job when Neo4j is down produces:

```
org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to neo4j:7687, ensure the database is running and that there is a working network connection to it.
```


Running a job with wrong authentication data produces:

```
org.neo4j.driver.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.
```

I think we are ok with this one. Thoughts? @moxious @conker84

**Comment by moxious** [comment]
I think you're right.
