### ISSUE TITLE
Sample code failed to execute

### ISSUE THREAD

**Issue by zhiboz** [neo4j-contrib/neo4j-spark-connector#2]
I am using Spark 1.6.1 together with Neo4j 3.0.3 (auth turned off). When trying to execute the sample code `Neo4jTupleRDD(sc,"cypher runtime=compiled MATCH (n) return id(n)",Seq.empty).count`, I encountered the following error

```
spark-shell --packages neo4j-contrib:neo4j-spark-connector:1.0.0-RC1
```

```
scala> Neo4jTupleRDD(sc,"cypher runtime=compiled MATCH (n) return id(n)",Seq.empty).count
16/06/26 19:21:16 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.neo4j.driver.v1.exceptions.ClientException: Invalid input 'u': expected 'e/E' (line 1, column 9 (offset: 8))
"runtime=compiled MATCH (n) return id(n)"
         ^
	at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:128)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:135)
	at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:150)
	at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:142)
	at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:303)
	at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:181)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1595)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
...
```

Any clue would be greatly appreciated!

**Comment by jexp** [comment]
Sorry in 3.0.3 the compiled runtime was temporarily removed to be re-added in 3.1
In the upcoming 3.0.4 it should work again, falling silently back to the interpreted runtime.
Just remove "cypher runtime=compiled" from the statements.

I'll adapt the examples in the readme.

**Comment by zhiboz** [comment]
Thanks @jexp fro the pointer! No wonder why it stopped working :). It works well after reverting back to `neo4j 3.0.2` .
