### ISSUE TITLE
Job submits fail on Google dataproc due to string formatting

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#202]
Job output:

```
Waiting for job output...
20/09/28 15:10:22 INFO org.spark_project.jetty.util.log: Logging initialized @2682ms
20/09/28 15:10:22 INFO org.spark_project.jetty.server.Server: jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
20/09/28 15:10:22 INFO org.spark_project.jetty.server.Server: Started @2773ms
20/09/28 15:10:22 INFO org.spark_project.jetty.server.AbstractConnector: Started ServerConnector@7bcefb27{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
20/09/28 15:10:23 WARN org.apache.spark.scheduler.FairSchedulableBuilder: Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure pools in fairscheduler.xml or set spark.scheduler.allocation.file to a file that contains the configuration.
20/09/28 15:10:23 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at sparky-m/10.156.0.3:8032
20/09/28 15:10:24 INFO org.apache.hadoop.yarn.client.AHSProxy: Connecting to Application History server at sparky-m/10.156.0.3:10200
20/09/28 15:10:26 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1601304760456_0008
20/09/28 15:10:31 INFO Driver: Routing driver instance 1122576521 created for server address 35.198.132.126:7687
20/09/28 15:10:31 INFO Driver: Closing driver instance 1122576521
20/09/28 15:10:32 INFO Driver: Routing driver instance 130345503 created for server address 35.198.132.126:7687
Traceback (most recent call last):
  File "/tmp/1b67afd0cd3d452f8316443dd41f22f3/script.py", line 13, in <module>
    .option("labels", "Theme") \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 350, in show
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o52.showString.
: java.lang.AbstractMethodError: org.neo4j.spark.reader.Neo4jDataSourceReader.createDataReaderFactories()Ljava/util/List;
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.readerFactories$lzycompute(DataSourceV2ScanExec.scala:55)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.readerFactories(DataSourceV2ScanExec.scala:52)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.inputRDD$lzycompute(DataSourceV2ScanExec.scala:76)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.inputRDD(DataSourceV2ScanExec.scala:60)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.inputRDDs(DataSourceV2ScanExec.scala:79)
	at org.apache.spark.sql.execution.ProjectExec.inputRDDs(basicPhysicalOperators.scala:41)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:622)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:337)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3284)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2495)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2495)
	at org.apache.spark.sql.Dataset$$anonfun$51.apply(Dataset.scala:3265)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3264)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2495)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2709)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

20/09/28 15:10:33 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@7bcefb27{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [1b67afd0cd3d452f8316443dd41f22f3] failed with error:
Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
https://console.cloud.google.com/dataproc/jobs/1b67afd0cd3d452f8316443dd41f22f3?project=testbed-187316&region=europe-west3
gcloud dataproc jobs wait '1b67afd0cd3d452f8316443dd41f22f3' --region 'europe-west3' --project 'testbed-187316'
https://console.cloud.google.com/storage/browser/sparky-cluster/google-cloud-dataproc-metainfo/613f6f46-611c-49b9-81fd-531a51bc76fb/jobs/1b67afd0cd3d452f8316443dd41f22f3/
gs://sparky-cluster/google-cloud-dataproc-metainfo/613f6f46-611c-49b9-81fd-531a51bc76fb/jobs/1b67afd0cd3d452f8316443dd41f22f3/driveroutput
```

**Comment by moxious** [comment]
Dataproc setup to reproduce. 

provision cluster:

```
gcloud dataproc clusters create sparky \
    --enable-component-gateway --bucket sparky-cluster --region europe-west3 \
    --subnet default --zone europe-west3-c --master-machine-type n1-standard-4 \
    --master-boot-disk-size 500 --num-workers 2 \
    --worker-machine-type n1-standard-4 --worker-boot-disk-size 500 \
    --image-version 1.3-debian10 \
    --optional-components ANACONDA,JUPYTER,ZEPPELIN \
    --project whatever
```

Script that I'm running:

```
from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
spark = SparkSession.builder.config(conf=SparkConf()).getOrCreate()

spark.read.format("org.neo4j.spark.DataSource") \
  .option("url", "neo4j+ssc://<endpoint>") \
  .option("authentication.basic.username", "neo4j") \
  .option("authentication.basic.password", "<password>") \
  .option("database", "neo4j") \
  .option("labels", "Theme") \
  .load().show()
```

Submitted to cluster like this:

```
#!/bin/bash

gcloud dataproc jobs submit pyspark \
    --cluster=sparky script.py \
    --jars=gs://sparky-cluster/neo4j-spark-connector-2.11-4.0.0.jar \
    --region=europe-west3
```

**Comment by moxious** [comment]
This issue may be related to an unsupported version of spark.  I tried a different Google Dataproc image for my spark cluster and got this different strange result:

(This is image 1.5-debian10 which is spark 2.4.6 and Scala 2.12.10)

```
Traceback (most recent call last):
  File "/tmp/7bb7984c42af4da8bf97003fb05e6ca7/script.py", line 13, in <module>
    .option("labels", "Person") \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 172, in load
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o53.load.
: java.lang.NoClassDefFoundError: scala/Product$class
	at org.neo4j.spark.Neo4jSchemaMetadata.<init>(Neo4jOptions.scala:166)
	at org.neo4j.spark.Neo4jOptions.<init>(Neo4jOptions.scala:36)
	at org.neo4j.spark.reader.Neo4jDataSourceReader.<init>(Neo4jDataSourceReader.scala:21)
	at org.neo4j.spark.DataSource.createReader(DataSource.scala:17)
	at org.neo4j.spark.DataSource.createReader(DataSource.scala:13)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:206)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

20/09/29 09:26:33 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@111bddda{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [7bb7984c42af4da8bf97003fb05e6ca7] failed with error:
Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
https://console.cloud.google.com/dataproc/jobs/7bb7984c42af4da8bf97003fb05e6ca7?project=testbed-187316&region=europe-west3
gcloud dataproc jobs wait '7bb7984c42af4da8bf97003fb05e6ca7' --region 'europe-west3' --project 'testbed-187316'
https://console.cloud.google.com/storage/browser/sparky-cluster/google-cloud-dataproc-metainfo/6cfe2636-749b-45e7-82d7-807ed10d66f7/jobs/7bb7984c42af4da8bf97003fb05e6ca7/
gs://sparky-cluster/google-cloud-dataproc-metainfo/6cfe2636-749b-45e7-82d7-807ed10d66f7/jobs/7bb7984c42af4da8bf97003fb05e6ca7/driveroutput
```

**Comment by conker84** [comment]
> This issue may be related to an unsupported version of spark. I tried a different Google Dataproc image for my spark cluster and got this different strange result:
> 
> (This is image 1.5-debian10 which is spark 2.4.6 and Scala 2.12.10)

@moxious yes I think that this is the problem, can you please try to build the version with scala 2.12?

`mvn clean package -Pscala-2.12 -DskipTests`

> 
> ```
> Traceback (most recent call last):
>   File "/tmp/7bb7984c42af4da8bf97003fb05e6ca7/script.py", line 13, in <module>
>     .option("labels", "Person") \
>   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 172, in load
>   File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
>   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
>   File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
> py4j.protocol.Py4JJavaError: An error occurred while calling o53.load.
> : java.lang.NoClassDefFoundError: scala/Product$class
> 	at org.neo4j.spark.Neo4jSchemaMetadata.<init>(Neo4jOptions.scala:166)
> 	at org.neo4j.spark.Neo4jOptions.<init>(Neo4jOptions.scala:36)
> 	at org.neo4j.spark.reader.Neo4jDataSourceReader.<init>(Neo4jDataSourceReader.scala:21)
> 	at org.neo4j.spark.DataSource.createReader(DataSource.scala:17)
> 	at org.neo4j.spark.DataSource.createReader(DataSource.scala:13)
> 	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
> 	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:206)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassNotFoundException: scala.Product$class
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 20 more
> 
> 20/09/29 09:26:33 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@111bddda{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
> ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [7bb7984c42af4da8bf97003fb05e6ca7] failed with error:
> Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
> https://console.cloud.google.com/dataproc/jobs/7bb7984c42af4da8bf97003fb05e6ca7?project=testbed-187316&region=europe-west3
> gcloud dataproc jobs wait '7bb7984c42af4da8bf97003fb05e6ca7' --region 'europe-west3' --project 'testbed-187316'
> https://console.cloud.google.com/storage/browser/sparky-cluster/google-cloud-dataproc-metainfo/6cfe2636-749b-45e7-82d7-807ed10d66f7/jobs/7bb7984c42af4da8bf97003fb05e6ca7/
> gs://sparky-cluster/google-cloud-dataproc-metainfo/6cfe2636-749b-45e7-82d7-807ed10d66f7/jobs/7bb7984c42af4da8bf97003fb05e6ca7/driveroutput
> ```

**Comment by moxious** [comment]
On me to verify this -- will do

**Comment by moxious** [comment]
Confirmed.  The scala 2.12 JAR fixes this issue.  I'm also adding a FAQ to the documentation to catch this.
