### ISSUE TITLE
How could i load graph with multiple properties from the node

### ISSUE THREAD

**Issue by madsnotepad** [neo4j-contrib/neo4j-spark-connector#23]
If I would like to load the vertices with multiple properties while loading graph, how could i do it.
The following loads only name in the vertices.
`val graphFrame = neo.pattern(("Person","name"),("KNOWS",null), ("Person","name")).partitions(3).rows(1000).loadGraphFrame`
Is there a way to load multiple properties from the neo4j nodes in the graph frames?

**Comment by deelam** [comment]
#25 seems relevant to you request.

**Comment by jexp** [comment]
I'm not sure if graphframes support multiple properties.

You can use a cypher statement and return the relevant properties as a map.

Something like this, but I have to test it out.

MATCH (n:Label)-[rel]->(m:Label)
RETURN id(n) as source, {foo: n.foo, bar: n.bar, type: type(rel) } as sourceProperty, id(m) as target, {key:value} as targetProperty

**Comment by madsnotepad** [comment]
I tried to load graph with cypher query but it failed with an exception. Not sure, if i am doing it the right way. I tried both with the properties and without properties. Both fail with the same exception. Says was expecting String but received null. When i run the cypher statement against neo4j instance it returns the resultset that contains no null for any of the returned values.

```
val graphF = Neo4j(sc).cypher("match (p:Person)-[r:KNOWS]->(a:Person) return id(p) as source, id(a) as target, type(r) as value").loadGraphFrame

org.neo4j.driver.v1.exceptions.ClientException: Unable to read MSG_RUN message. Error was: Wrong type received. Expected STRING, received: NULL (0xff).
        at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
        at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
        at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:135)
        at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:150)
        at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:170)
        at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:303)
        at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:181)
        at org.neo4j.spark.Executor$.execute(Neo4j.scala:363)
        at org.neo4j.spark.Neo4jRDD.compute(Neo4j.scala:408)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
16/10/16 06:43:55 WARN TaskSetManager: Lost task 0.0 in stage 43.0 (TID 44, localhost): org.neo4j.driver.v1.exceptions.ClientException: Unable to read MSG_RUN message. Error was: Wrong type received. Expected STRING, received: NULL (0xff).
        at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
        at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
        at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:135)
        at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:150)
        at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:170)
        at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:303)
        at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:181)
        at org.neo4j.spark.Executor$.execute(Neo4j.scala:363)
        at org.neo4j.spark.Neo4jRDD.compute(Neo4j.scala:408)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by madsnotepad** [comment]
Deelam, Thank you. The issue 25 is for loading data frames. I am trying to load graph frames.

**Comment by jexp** [comment]
Do you have an example of what it returns? Could you share your db?

Von meinem iPhone gesendet

**Comment by jexp** [comment]
Ok, sorry my bad.

For graph-frame you currently have to provide relationship and node query, like this:
I add an error message if one is missing.

```
import org.neo4j.spark._

val nodesQuery = "match (n:Officer) RETURN id(n) as id UNION ALL MATCH (n:Entity) return id(n) as id"
val relsQuery = "match (p:Officer)-[r]->(e:Entity) return id(p) as src, id(e) as dst, type(r) as value"

val graphF = Neo4j(sc).nodes(nodesQuery,Map.empty).rels(relsQuery,Map.empty).loadGraphFrame

scala> graphF.vertices.count
res7: Long = 864721

scala> graphF.edges.count
res8: Long = 591147
```

**Comment by jexp** [comment]
Or this if you want to transfer values into the graphframe

```
import org.neo4j.spark._

val nodesQuery = "match (n:Officer) RETURN id(n) as id, n.name as value UNION ALL MATCH (n:Entity) return id(n) as id, n.name as value"
val relsQuery = "match (p:Officer)-[r]->(e:Entity) return id(p) as src, id(e) as dst, type(r) as value"

val graphF = Neo4j(sc).nodes(nodesQuery,Map.empty).rels(relsQuery,Map.empty).loadGraphFrame
```

**Comment by madsnotepad** [comment]
Thank you Michael. I shall give it a try and keep you posted. I do this for my learning and during off hours so my response may be delayed.

**Comment by madsnotepad** [comment]
Michael, the one you suggested works well. Thank you.

> val graphF = Neo4j(sc).nodes(nodesQuery,Map.empty).rels(relsQuery,Map.empty).loadGraphFrame

**Comment by jexp** [comment]
Cool

**Comment by asarraf** [comment]
@jexp 
`scala> val df = neo.cypher("match (n:Emp) return id(n) as id, n.name as name, n.dept as dept").loadDataFrame(("id"->"long"),("name"->"string"),("dept"->"long"))
df: org.apache.spark.sql.DataFrame = [id: bigint, name: string ... 1 more field]

scala> df.count()
res15: Long = 28  // When I have only 7 nodes in my Graph. Any specific reason for this repetitions?
`

**Comment by Felix1990** [comment]
> Cool

Does it mean that Map.empty is for querying multiple properties?

**Comment by Felix1990** [comment]
> Cool

I mean that one node with multiple properties(like: name, age etc.)
