### ISSUE TITLE
Cypher query returning node doesn't work with Spark 

### ISSUE THREAD

**Issue by kaxil** [neo4j-contrib/neo4j-spark-connector#24]
When I try to run this command:

```
val xyz = Neo4jRowRDD(sc,"MATCH (n:Officers) WHERE n.Person_Number = {PeID} RETURN n",Seq("PeID"->"142685420002"))
xyz.take(1)
```

I get the following error:

```

16/09/19 15:18:52 ERROR Executor: Exception in task 0.0 in stage 7.0 (TID 7)
java.io.NotSerializableException: org.neo4j.driver.internal.InternalNode
Serialization stack:
    - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<10516047>)
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1)
    - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
    - object (class org.apache.spark.sql.catalyst.expressions.GenericRow, [node<10516047>])
    - element of array (index: 0)
    - array (class [Lorg.apache.spark.sql.Row;, size 1)
    at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
    at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
    at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
16/09/19 15:18:52 ERROR TaskSetManager: Task 0.0 in stage 7.0 (TID 7) had a not serializable result: org.neo4j.driver.internal.InternalNode
Serialization stack:
    - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<10516047>)
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1)
    - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
    - object (class org.apache.spark.sql.catalyst.expressions.GenericRow, [node<10516047>])
    - element of array (index: 0)
    - array (class [Lorg.apache.spark.sql.Row;, size 1); not retrying
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 7.0 (TID 7) had a not serializable result: org.neo4j.driver.internal.InternalNode
Serialization stack:
    - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<10516047>)
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1)
    - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
    - object (class org.apache.spark.sql.catalyst.expressions.GenericRow, [node<10516047>])
    - element of array (index: 0)
    - array (class [Lorg.apache.spark.sql.Row;, size 1)
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
...
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1279)
```

**Note:**
I came to know however that there is a workaround that we would have to **turn nodes into maps**. That is **don't return the node but it's id or a property**; use something like 

```
val rdd = neo.cypher("MATCH (n:Officers) RETURN n.Person_Number as id,n.Address_Line_1 as Address limit 5").loadRowRdd
```

instead of 

```
val rdd = neo.cypher("MATCH (n:Officers) RETURN n.Person_Number, n.Address_Line_1 limit 5").loadRowRdd
```

**Comment by jexp** [comment]
you could also return properties(n)

What is your use-case for returning the full node data?
We could add some code within the connector that turns nodes / relationships into constructs that Spark can work with, e.g maps or flattened objects, but that would require quite some magic which might be confusing for users. 

So perhaps an error message that points out `properties(n)` or even a map projection like: `n { id: id(n), labels: labels(n), .* } as node` would make more sense?

**Comment by jexp** [comment]
Also nodes in Neo4j can have different number (and types) of attributes, so flattening them out into columns automatically wouldn't work really well.
