### ISSUE TITLE
Unwind on array of objects crashes

### ISSUE THREAD

**Issue by aaramg** [neo4j-contrib/neo4j-spark-connector#265]
Hi.
Here is my code I want to run and do writing in Neo4j and I get an error.
I don't know from where it takes "type" field name. I guess the problem is coming from UNWIND on array of objects.
I guess it does not work as expected.

```
sparkVersion = "2.4.7"
scalaVersion = "2.12.12"
neo4jConnectorVersion = "4.0.0"
jdkVersion = "14"
```
```
case class User(id: String, firstName: String, lastName: String, gender: String, birthday: String, email: String, arrayOfObjects: Array[Obj])
case class Obj(objStringField1: String, objStringField2: String)
```
Smth like this:
```
{
  "id": "df25368a-49a1-4843-9d49-dd7de700763e",
  "firstName": "Rolfe",
  "lastName": "Noyce",
  "gender": "MALE",
  "birthday": "2000-12-19T04:00:00.000+04:00",
  "email": "rnoyce1@google.co.uk",
  "arrayOfObjects": [
    {
      "objStringField1": "test1",
      "objStringField2": "test2"
    }
  ]
}
```

```
    users.write
      .format("org.neo4j.spark.DataSource")
      .option("database", "{my-db}")
      .option("url", "bolt://{my-neo4j-server}")
      .option("authentication.basic.username", "{my-username}")
      .option("authentication.basic.password", "{my-password}")
      .mode(SaveMode.Overwrite)
      .option("query",
        """
          |UNWIND $event.arrayOfObjects as obj
          |MERGE (u:User {id: event.id, firstName: event.firstName, lastName: event.lastName, gender: event.gender, birthday: event.birthday, email: event.email, userProp: obj.objStringField1})
          |""".stripMargin)
      .save()
```
It crashes. Here is the stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Field "type" does not exist.
Available fields: objStringField1, objStringField2
    at org.apache.spark.sql.types.StructType.$anonfun$fieldIndex$1(StructType.scala:305)
    at scala.collection.immutable.Map$Map2.getOrElse(Map.scala:222)
    at org.apache.spark.sql.types.StructType.fieldIndex(StructType.scala:303)
    at org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema.fieldIndex(rows.scala:187)
    at org.neo4j.spark.util.Neo4jUtil$.convertFromSpark(Neo4jUtil.scala:171)
    at org.neo4j.spark.util.Neo4jUtil$.$anonfun$convertFromSpark$1(Neo4jUtil.scala:197)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
    at scala.collection.Iterator.foreach(Iterator.scala:943)
    at scala.collection.Iterator.foreach$(Iterator.scala:943)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
    at scala.collection.IterableLike.foreach(IterableLike.scala:74)
    at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
    at org.apache.spark.sql.catalyst.util.ArrayDataIndexedSeq.foreach(ArrayData.scala:205)
    at scala.collection.TraversableLike.map(TraversableLike.scala:285)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
    at org.apache.spark.sql.catalyst.util.ArrayDataIndexedSeq.map(ArrayData.scala:205)
    at org.neo4j.spark.util.Neo4jUtil$.convertFromSpark(Neo4jUtil.scala:197)
    at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1(MappingService.scala:125)
    at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1$adapted(MappingService.scala:123)
    at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
    at scala.collection.immutable.Range.foreach(Range.scala:158)
    at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
    at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
    at org.neo4j.spark.service.Neo4jWriteMappingStrategy.query(MappingService.scala:123)
    at org.neo4j.spark.service.Neo4jWriteMappingStrategy.query(MappingService.scala:20)
    at org.neo4j.spark.service.MappingService.convert(MappingService.scala:234)
    at org.neo4j.spark.writer.Neo4jDataWriter.write(Neo4jDataWriter.scala:41)
    at org.neo4j.spark.writer.Neo4jDataWriter.write(Neo4jDataWriter.scala:20)
    at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$2(WriteToDataSourceV2Exec.scala:118)
    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
    at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:116)
    at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.$anonfun$doExecute$2(WriteToDataSourceV2Exec.scala:67)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
    at org.apache.spark.scheduler.Task.run(Task.scala:123)
    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
```

**Comment by utnaf** [comment]
Hi @aaramg! Thanks for the detailed report 🙏  We actually found a bug on our side. We'll fix it asap! I'll keep you posted.

Thanks for the catch

**Comment by utnaf** [comment]
Hi @aaramg, here's the PR that fixes this #267 

Here you can find the jar packaged from that PR, let me know if your issue is fixed.
[neo4j-connector-apache-spark_2.11-4.0.0_patch_265.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/5679988/neo4j-connector-apache-spark_2.11-4.0.0_patch_265.jar.zip)

**Comment by aaramg** [comment]
Hi @utnaf 
Thank you for such a great and fast support. I tried the jar which you gave me. But now I get this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at org.neo4j.spark.Neo4jSchemaMetadata.<init>(Neo4jOptions.scala:177)
	at org.neo4j.spark.Neo4jOptions.<init>(Neo4jOptions.scala:40)
	at org.neo4j.spark.writer.Neo4jDataSourceWriter.<init>(Neo4jDataSourceWriter.scala:21)
	at org.neo4j.spark.DataSource.createWriter(DataSource.scala:26)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:277)
```
I guess maybe one of these versions causes this error (especially scala version):
```
sparkVersion = "2.4.7"
scalaVersion = "2.12.12"
neo4jConnectorVersion = "4.0.0"
jdkVersion = "14"
```
I cannot change Scala version to 2.11. It will make crashes on the other libs. Could you plz help me to figure out. I guess you should give me 2.12 version of the jar smth like this: neo4j-connector-apache-spark_**2.12**-4.0.0_patch_265.jar.zip
Thanks in advance

**Comment by utnaf** [comment]
Ops... my bad @aaramg ! Totally forgot to check your scala version.

Just so you know, this connector is packaged with Spark 2.4.5 but shouldn't be a big deal.

[neo4j-connector-apache-spark_2.12-4.0.0_patch_265.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/5682677/neo4j-connector-apache-spark_2.12-4.0.0_patch_265.jar.zip)

**Comment by aaramg** [comment]
Hi @utnaf it worked. Thank you for your support. :)

**Comment by utnaf** [comment]
Welcome! Have a great weekend and stay safe :)
