### ISSUE TITLE
Not able to Insert Neo4j Map Data type using the neo4j-spark connector

### ISSUE THREAD

**Issue by ashishagarwal1983** [neo4j-contrib/neo4j-spark-connector#315]
Spark 3.0.0
Scala 2.12 
Neo4j 4.2.4

We have enabled apoc procedures in neo4j and getting below errror while saving the data using neo4j spark connector, We have listed schema and data example at the end of stack trace

```
org.neo4j.driver.exceptions.ClientException: Unable to convert org.apache.spark.unsafe.types.UTF8String to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.Values.value(Values.java:297)
	at org.neo4j.driver.Values.value(Values.java:119)
	at org.neo4j.spark.util.Neo4jUtil$.convertFromSpark(Neo4jUtil.scala:213)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1(MappingService.scala:123)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1$adapted(MappingService.scala:121)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.query(MappingService.scala:121)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.node(MappingService.scala:30)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.node(MappingService.scala:18)
	at org.neo4j.spark.service.MappingService.convert(MappingService.scala:230)
	at org.neo4j.spark.writer.BaseDataWriter.write(BaseDataWriter.scala:37)
	at org.neo4j.spark.writer.Neo4jDataWriter.write(Neo4jDataWriter.scala:9)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

________________________________________________________________________________________
My neo4jDF printschema output

```
root
 |-- id: long (nullable = false)
 |-- name: string (nullable = true)
 |-- allOtherAttributes: map (nullable = true)
 |    |-- key: string
 |    |-- value: string (valueContainsNull = true)
``` 

Sample Data in neo4jDF

```
+----------+-------------------+-----------------------------------------+
|    id    |name               |allOtherAttributes                       |
+----------+-------------------+-----------------------------------------+
|7028701946|Pediatric Dentistry|[type -> hospital, healthcare -> dentist]|
+----------+-------------------+-----------------------------------------+
```

Used the following option to write the data to neo4j 

```
neo4jDF.write
     .format("org.neo4j.spark.DataSource")
     .mode(SaveMode.Append)
     .option("url", "bolt://localhost:7687")
     .option("authentication.basic.username", "username")
     .option("authentication.basic.password", "password").option("multiline", "true").option("database","neo4jdb")
     .option("labels", ":Hospital")
     .save()
```

**Comment by utnaf** [comment]
Hi @ashishagarwal1983, we found and fixed the issue. 

Please try this JAR and let us know if this fixed your issue!
[neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/6277549/neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar.zip)

**Comment by ashishagarwal1983** [comment]
Thanks This jar is working for me as expected ? when is the official release planned for this ?

**Comment by conker84** [comment]
hi @ashishagarwal1983 we are focusing now on new features such as Structured Streaming support, I think that we can do a new release by the end of the month
