### ISSUE TITLE
How to connect to neo4j in worker node?

### ISSUE THREAD

**Issue by Mazzjs** [neo4j-contrib/neo4j-spark-connector#32]
I need to get a small subgraph when doing map function. But when I used NEO4J class in a map function, I got "Task not serializable" exception:
```
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2094)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:793)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:792)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:792)
	at placeGraph$.main(placeGraph.scala:170)
	at placeGraph.main(placeGraph.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.NotSerializableException: org.neo4j.spark.Neo4j
Serialization stack:
	- object not serializable (class: org.neo4j.spark.Neo4j, value: org.neo4j.spark.Neo4j@1736c1e4)
	- field (class: placeGraph$$anonfun$18, name: neo$1, type: class org.neo4j.spark.Neo4j)
	- object (class placeGraph$$anonfun$18, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 16 more
```

**Comment by jexp** [comment]
Can you share your actual code, without it, we can't help you.
You should only create the Neo4j object within your job and not pass it through.

**Comment by Mazzjs** [comment]
hi , @jexp,  thanks for your attention, my code is like this : 
````
val neo = Neo4j(sc) // this runs on the driver

// this runs by a map function
def someFunctionToBeMapped(p: List[Long]) = { 
  val metaGraph = neo.cypher("match p = (a:TourPlace) -[r:could_go_to] -> (b:TourPlace)" +
    "return a.id ,r.distance, b.id").loadRowRdd.map( row => ((row(0).asInstanceOf[Long],row(2).asInstanceOf[Long]), row(1).asInstanceOf[Double]) ).collect().toList
````

**Comment by jexp** [comment]
Thanks a lot, I'll check it.

Can you see if this works:

```
// this runs by a map function
def someFunctionToBeMapped(p: List[Long]) = { 
  val neo = Neo4j(sc) // this runs on the driver
  val metaGraph = neo.cypher("match p = (a:TourPlace) -[r:could_go_to] -> (b:TourPlace)" +
    "return a.id ,r.distance, b.id").loadRowRdd.map( row => ((row(0).asInstanceOf[Long],row(2).asInstanceOf[Long]), row(1).asInstanceOf[Double]) ).collect().toList
```

**Comment by Mazzjs** [comment]
Hi, @jexp .
I tried this, it doesn't work :<. This will lead a "org.apache.spark.SparkContext" not serializable issue.  I guess that  the Neo4j Connection has bound with the driver machine just like Spark Context,  so when I try to use map function, spark can't serialize it. Do you know any other way to do such connection? Or are there some methods to connect to neo4j "directly" using mapPartition function? 
```
Caused by: java.io.NotSerializableException: org.apache.spark.SparkContext
Serialization stack:
	- object not serializable (class: org.apache.spark.SparkContext, value: org.apache.spark.SparkContext@738a815c)
	- field (class: placeGraph$$anonfun$18, name: sc$1, type: class org.apache.spark.SparkContext)
	- object (class placeGraph$$anonfun$18, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 16 more

```

**Comment by jexp** [comment]
Actually it should not in the Neo4j instance 
I went to great lengths to make sure it's serializable. 

I check your case as soon as I have time 

Von meinem iPhone gesendet

**Comment by jexp** [comment]
The SparkContext should be available as implicit to your function, can you try that?
Or add it directly as implicit parameter.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
