### ISSUE TITLE
Error downloading neo4j-contrib:neo4j-connector-apache-spark_2.11:4.0.1_for_spark_2.4

### ISSUE THREAD

**Issue by kennyishihara** [neo4j-contrib/neo4j-spark-connector#339]
I'm using the below in build.sbt

```
resolvers ++= Seq(
  "Spark Packages Repo" at "https://dl.bintray.com/spark-packages/maven"
)

libraryDependencies ++= Seq(
  "neo4j-contrib" % "neo4j-connector-apache-spark_2.11" % "4.0.1_for_spark_2.4"
)
```

and it is giving me an error 

```
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading neo4j-contrib:neo4j-connector-apache-spark_2.11:4.0.1_for_spark_2.4
[error]   Not found
[error]   not found: /Users/kenny/.ivy2/localneo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1_for_spark_2.4/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.1_for_spark_2.4.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.1_for_spark_2.4.pom (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.1_for_spark_2.4.pom) while downloading https://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.1_for_spark_2.4.pom
```

**Comment by utnaf** [comment]
Hi, sorry but I think we have a naming issue. Can you please try using `4.0.1` instead of `4.0.1_for_spark_2.4`?

```
resolvers ++= Seq(
  "Spark Packages Repo" at "https://dl.bintray.com/spark-packages/maven"
)

libraryDependencies ++= Seq(
  "neo4j-contrib" % "neo4j-connector-apache-spark_2.11" % "4.0.1"
)
```

I will update the docs today. Thank you

**Comment by kennyishihara** [comment]
@utnaf I am still getting the same error. 

Could it be due to bintray service shutting down? Appears from this tweet https://twitter.com/bintray/status/1388211300635856896 that the service was shut down May 1st, 2021. Just a few days ago. 

I would like to know if others can replicate this error. 

Thank you!

**Comment by utnaf** [comment]
Bintray has been sunset, the repo should be usable until Feb 2022.

I link #334. It's about moving to Maven 2. 

I'll make some tests later in the morning and get back to you asap.

**Comment by badrinathpatchikolla** [comment]
Facing a Similar issue I think bintray service is down for both the versions of neo4j spark connector

```scala
spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.11:4.0.0
Ivy Default Cache set to: /home/ma0080u/.ivy2/cache
The jars for the packages stored in: /home/ma0080u/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-6.2.1-1.cdh6.2.1.p0.1425774/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
neo4j-contrib#neo4j-connector-apache-spark_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f37bff73-2a37-4360-969d-ac000c696a42;1.0
        confs: [default]
:: resolution report :: resolve 1803ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0

        ==== local-m2-cache: tried

          file:/home/ma0080u/.m2/repository/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0!neo4j-connector-apache-spark_2.11.jar:

          file:/home/ma0080u/.m2/repository/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.jar

        ==== local-ivy-cache: tried

          /home/ma0080u/.ivy2/local/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/ivys/ivy.xml

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0!neo4j-connector-apache-spark_2.11.jar:

          /home/ma0080u/.ivy2/local/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/jars/neo4j-connector-apache-spark_2.11.jar

        ==== central: tried

          https://repo1.maven.org/maven2/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0!neo4j-connector-apache-spark_2.11.jar:

          https://repo1.maven.org/maven2/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0!neo4j-connector-apache-spark_2.11.jar:

          http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.0/neo4j-connector-apache-spark_2.11-4.0.0.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.0: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1308)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
```scala
spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.11:4.0.1
Ivy Default Cache set to: /home/ma0080u/.ivy2/cache
The jars for the packages stored in: /home/ma0080u/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-6.2.1-1.cdh6.2.1.p0.1425774/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
neo4j-contrib#neo4j-connector-apache-spark_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-72a9566c-451c-467c-9e24-03f7cd10e363;1.0
        confs: [default]
:: resolution report :: resolve 1872ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1

        ==== local-m2-cache: tried

          file:/home/ma0080u/.m2/repository/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1!neo4j-connector-apache-spark_2.11.jar:

          file:/home/ma0080u/.m2/repository/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.jar

        ==== local-ivy-cache: tried

          /home/ma0080u/.ivy2/local/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/ivys/ivy.xml

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1!neo4j-connector-apache-spark_2.11.jar:

          /home/ma0080u/.ivy2/local/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/jars/neo4j-connector-apache-spark_2.11.jar

        ==== central: tried

          https://repo1.maven.org/maven2/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1!neo4j-connector-apache-spark_2.11.jar:

          https://repo1.maven.org/maven2/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.pom

          -- artifact neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1!neo4j-connector-apache-spark_2.11.jar:

          http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/4.0.1/neo4j-connector-apache-spark_2.11-4.0.1.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: neo4j-contrib#neo4j-connector-apache-spark_2.11;4.0.1: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1308)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by utnaf** [comment]
Quick update, we are getting the same issue. Until we figure this out I suggest you to download the JAR directly from [here](https://neo4j.com/product/connectors/apache-spark-connector/) or from the [release page](https://github.com/neo4j-contrib/neo4j-spark-connector/releases).

**Comment by utnaf** [comment]
Hi there! Closing the issue because now the Neo4j Connector for Apache Spark is available on maven 🎉 

https://search.maven.org/search?q=g:org.neo4j%20AND%20a:neo4j-connector-apache-spark_2.12
https://search.maven.org/search?q=g:org.neo4j%20AND%20a:neo4j-connector-apache-spark_2.11

You can follow the instructions on the documentation https://neo4j.com/developer/spark/quickstart/#_using_maven

**Comment by praveenkumarb1207** [comment]
Hey ! I am using the new connector version 4.0.2_for_spark_2.4 for scala 2.11 and scala 2.12 with spark version 2.4.5. 

I am getting the below error while writing to neo4j using connector with scala 2.11 and spark 2.4.5 

```
com.github.music.of.the.ainur.almaren.neo4j.Test *** ABORTED ***
[info]   java.lang.NoSuchMethodError: org.apache.spark.internal.Logging.$init$(Lorg/apache/spark/internal/Logging;)V
[info]   at org.neo4j.spark.util.Validations$.<init>(Validations.scala:10)
[info]   at org.neo4j.spark.util.Validations$.<clinit>(Validations.scala)
[info]   at org.neo4j.spark.DataSource.<init>(DataSource.scala:16)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
```

The same version is working for scala 2.12 and spark 2.4.5 when writng to neo4j.  

Do you have any solution for the scala 2.11 and spark 2.4.5 version ?

**Comment by utnaf** [comment]
Hi! Can you tell me which exact version for the connector you are using? 

If you need to make it work for Scala 2.11 and Spark 2.4.5 you should use this one https://search.maven.org/artifact/org.neo4j/neo4j-connector-apache-spark_2.11/4.0.2_for_spark_2.4/jar

**Comment by praveenkumarb1207** [comment]
I am using 

"org.neo4j:neo4j-connector-apache-spark_2.11:4.0.2_for_spark_2.4" -  for scala 2.11 and spark 2.4.5 - getting the error as I mentioned earlier

"org.neo4j:neo4j-connector-apache-spark_2.12:4.0.2_for_spark_2.4" - for scala 2.12 and spark 2.4.5 -  Working

**Comment by utnaf** [comment]
Can you please open a new issue and sharing the code? Thank you

**Comment by praveenkumarb1207** [comment]
Sure . Thank you !
