### ISSUE TITLE
Neo4j Spark Connector integration with pyspark

### ISSUE THREAD

**Issue by surbhigupta546** [neo4j-contrib/neo4j-spark-connector#347]
Hi,
I'm trying to read nodes from my local neo4jdb for practice purposes by using pyspark and neo4j connector. I've already downloaded the last version of neo4j-connector-apache-spark (2.12) and integrated it in pyspark as explained in the repo.

Spark version :- 3.0
neo4j-connector used :- neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3

when I am trying to run the peice of code in pycharm :- 

```scala
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[1]") \
    .appName("Neo4jConnection")\
    .getOrCreate()
query = """
    
"""

df = spark.read.format("org.neo4j.spark.DataSource") \
  .option("url", "bolt://localhost:7687") \
    .option("authentication.type", "basic") \
    .option("authentication.basic.username", "neo4j") \
    .option("authentication.basic.password", "pss") \
    .option("query", query) \
    .option("partitions", "1") \
    .load()
```

I am getting the attached error:
```  
: java.lang.AbstractMethodError: Method org/neo4j/spark/DataSource.getTable(Lorg/apache/spark/sql/util/CaseInsensitiveStringMap;)Lorg/apache/spark/sql/connector/catalog/Table; is abstract
```

<img width="893" alt="errorpyspark" src="https://user-images.githubusercontent.com/84117196/118080897-2c271a00-b3d8-11eb-99bb-ef8d145785df.PNG">

@conker84 , If you can help out on this, it be great!

**Comment by surbhigupta546** [comment]
I have already placed the jar in %SPARK_HOME%/jars

**Comment by surbhigupta546** [comment]
@utnaf @conker84 @moxious

**Comment by surbhigupta546** [comment]
https://community.neo4j.com/t/neo4j-spark-connector-integration-with-pyspark-using-pycharm/38250 
Raised in Neo4j community as well.

**Comment by utnaf** [comment]
Hi @surbhigupta546, sorry for the delay but we are in a different timezone and I personally was sleeping. I'm running some tests and will get back to you.

**Comment by surbhigupta546** [comment]
Thanks @utnaf .

**Comment by utnaf** [comment]
I tried with Databricks environment, command line Pyspark, and also with a Zeppelin notebook. I wasn't able to reproduce the issue. 

Can you give me the details of how you are trying to run the code? Python version, exact Spark version (3.0.1 I guess?).
Can you paste the whole output of the error?

**Comment by surbhigupta546** [comment]
Set Environment variables PYSPARK_PYTHON  & SPARK_HOME
I am using Pycharm with Anaconda (conda 4.9.2). 
I configured the interpreter with Conda and placed the pyspark and py4j from my spark folder to  (C:\Software\Annaconda\envs\pyspark3\Lib\site-packages) {pyspark3 --> folder where my project is located}.
Using Pyspark (__version__='3.0.0.dev2')
Then :- 
I have placed the jar(connector) in the %SPARK_HOME%/jars  folder.
I wrote the above code.
while running faced issue :- 
```
Traceback (most recent call last):
  File "C:\Gitlab Code\Udemy_learningJournal\Spark-Programming-In-Python\21-Neo4jConnector\Neo4jConnection.py", line 18, in <module>
    df = spark.read.format("org.neo4j.spark.DataSource") \
  File "C:\Software\Annaconda\envs\pyspark3\lib\site-packages\pyspark\sql\readwriter.py", line 166, in load
    return self._df(self._jreader.load())
  File "C:\Software\Annaconda\envs\pyspark3\lib\site-packages\py4j\java_gateway.py", line 1285, in __call__
    return_value = get_return_value(
  File "C:\Software\Annaconda\envs\pyspark3\lib\site-packages\pyspark\sql\utils.py", line 98, in deco
    return f(*a, **kw)
  File "C:\Software\Annaconda\envs\pyspark3\lib\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o38.load.
: java.lang.AbstractMethodError: Method org/neo4j/spark/DataSource.getTable(Lorg/apache/spark/sql/util/CaseInsensitiveStringMap;)Lorg/apache/spark/sql/connector/catalog/Table; is abstract
	at org.neo4j.spark.DataSource.getTable(DataSource.scala)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:220)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:206)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


Process finished with exit code 1
```

**Comment by surbhigupta546** [comment]
Please try using Pycharm and Anaconda if possible , cause I dont have an option to use Zeppelin notebook.

**Comment by utnaf** [comment]
I see you are using a non-stable version of pyspark, please use a stable version (3.0.2 or 3.1.1) and let me know.

You can also clone this repository https://github.com/utnaf/neo4j-connector-apache-spark-notebooks and run `docker-compose up` and you have a fully working Zeppelin environment with notebook examples and a Neo4j database.

You can play around with that, I also just pushed a new notebook with you exact example, it's called "Pyspark".

Let me know.

**Comment by surbhigupta546** [comment]
Thanks @utnaf . I had upgraded the pyspark version and it worked!

**Comment by utnaf** [comment]
Great to hear. I'll close this and I'll update the question on the community as well.
