### ISSUE TITLE
Cannot import relationships properly from Neo4j sample Movie database and can;t select columns in Pyspark

### ISSUE THREAD

**Issue by RGEv1L** [neo4j-contrib/neo4j-spark-connector#381]
spark: 3.0.3
pyspark: 3.0.3
scala: 2.12
neo4j connector: neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3

```python
from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('RS1')\
	.master("spark://'some-url':7077") \
	.config('spark.executor.memory','1000m') \
	.config("spark.jars.packages","graphframes:graphframes:0.8.0-spark3.0-s_2.12,neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3")\
 	.getOrCreate()

dfr = spark.read.format("org.neo4j.spark.DataSource")\
  .option("url", "bolt://'some-url':7687")\
  .option("authentication.basic.username", "some-uname'")\
  .option("authentication.basic.password", "some-pass")\
  .option("pushdown.columns.enabled", "false")\
  .option("relationship", "ACTED_IN")\
  .option("relationship.source.labels", "Person")\
  .option("relationship.target.labels", "Movie")\
  .load()
```

i get this error:
```
21/07/13 23:55:04 WARN SchemaService: Switching to query schema resolution
21/07/13 23:55:04 WARN SchemaService: Switching to query schema resolution
21/07/13 23:55:04 WARN SchemaService: Switching to query schema resolution
21/07/13 23:55:04 WARN SchemaService: For the following exception
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.service.SchemaService.retrieveSchemaFromApoc(SchemaService.scala:68)
	at org.neo4j.spark.service.SchemaService.liftedTree2$1(SchemaService.scala:171)
	at org.neo4j.spark.service.SchemaService.structForRelationship(SchemaService.scala:155)
	at org.neo4j.spark.service.SchemaService.struct(SchemaService.scala:262)
	at org.neo4j.spark.DataSource.$anonfun$inferSchema$1(DataSource.scala:41)
	at org.neo4j.spark.DataSource.callSchemaService(DataSource.scala:29)
	at org.neo4j.spark.DataSource.inferSchema(DataSource.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

but when I run dfr.columns , I get these.
['<rel.id>', '<rel.type>', '<source.id>', '<source.labels>', 'source.name', 'source.born', '<target.id>', '<target.labels>', 'target.title', 'target.tagline', 'target.released', 'rel.roles']

but I am being able to select any of those columns with dfr.select('<rel.id>')

I have used all of the strategies for push-down filters for columns etc but failed...

**Comment by utnaf** [comment]
Hi! Can you trying using the 4.0.2 version and let me know if the error still there?

**Comment by RGEv1L** [comment]
@utnaf  still getting the same error and also cannot select the columns as well

```
21/07/14 17:11:35 WARN SchemaService: Switching to query schema resolution
21/07/14 17:11:35 WARN SchemaService: Switching to query schema resolution
21/07/14 17:11:35 WARN SchemaService: Switching to query schema resolution
21/07/14 17:11:35 WARN SchemaService: For the following exception
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.service.SchemaService.retrieveSchemaFromApoc(SchemaService.scala:68)
	at org.neo4j.spark.service.SchemaService.liftedTree2$1(SchemaService.scala:171)
	at org.neo4j.spark.service.SchemaService.structForRelationship(SchemaService.scala:155)
	at org.neo4j.spark.service.SchemaService.struct(SchemaService.scala:262)
	at org.neo4j.spark.DataSource.$anonfun$inferSchema$1(DataSource.scala:41)
	at org.neo4j.spark.DataSource.callSchemaService(DataSource.scala:29)
	at org.neo4j.spark.DataSource.inferSchema(DataSource.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

dfr.show()


```
+--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
|<rel.id>|<rel.type>|<source.id>|<source.labels>|       source.name|source.born|<target.id>|<target.labels>|        target.title|      target.tagline|target.released|           rel.roles|
+--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
|       7|  ACTED_IN|          8|       [Person]|       Emil Eifrem|       1978|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|              [Emil]|
|       3|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|       [Agent Smith]|
|       2|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|          [Morpheus]|
|       1|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|           [Trinity]|
|       0|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|               [Neo]|
|      11|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|       [Agent Smith]|
|      10|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|          [Morpheus]|
|       9|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|           [Trinity]|
|       8|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|               [Neo]|
|      18|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|       [Agent Smith]|
|      17|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|          [Morpheus]|
|      16|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|           [Trinity]|
|      15|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|               [Neo]|
|      24|  ACTED_IN|         13|       [Person]|         Al Pacino|       1940|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|       [John Milton]|
|      23|  ACTED_IN|         12|       [Person]|   Charlize Theron|       1975|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|    [Mary Ann Lomax]|
|      22|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|       [Kevin Lomax]|
|      35|  ACTED_IN|         25|       [Person]|    James Marshall|       1967|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|[Pfc. Louden Downey]|
|      33|  ACTED_IN|         23|       [Person]|      Kevin Pollak|       1957|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|  [Lt. Sam Weinberg]|
|      34|  ACTED_IN|         24|       [Person]|        J.T. Walsh|       1943|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|[Lt. Col. Matthew...|
|      37|  ACTED_IN|         28|       [Person]|      Aaron Sorkin|       1961|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|        [Man in Bar]|
+--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
only showing top 20 rows
```

dfr.columns

```
['<rel.id>', '<rel.type>', '<source.id>', '<source.labels>', 'source.name', 'source.born', '<target.id>', '<target.labels>', 'target.title', 'target.tagline', 'target.released', 'rel.roles']
```

dfr.select('<rel.id>')

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyspark/sql/dataframe.py", line 1421, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.6/site-packages/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: cannot resolve '`<rel.id>`' given input columns: [<rel.id>, <rel.type>, <source.id>, <source.labels>, <target.id>, <target.labels>, rel.roles, source.born, source.name, target.released, target.tagline, target.title];;
'Project ['<rel.id>]
+- RelationV2[<rel.id>#134L, <rel.type>#135, <source.id>#136L, <source.labels>#137, source.name#138, source.born#139L, <target.id>#140L, <target.labels>#141, target.title#142, target.tagline#143, target.released#144L, rel.roles#145] table_Person_ACTED_IN_Movie
```

**Comment by utnaf** [comment]
I'm having troubles understanding what code gives you this error

```
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
```

This code you posted in the initial issue is correct and works properly since you can show the content of the dataframe.

```python
from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('RS1')\
	.master("spark://'some-url':7077") \
	.config('spark.executor.memory','1000m') \
	.config("spark.jars.packages","graphframes:graphframes:0.8.0-spark3.0-s_2.12,neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3")\
 	.getOrCreate()

dfr = spark.read.format("org.neo4j.spark.DataSource")\
  .option("url", "bolt://'some-url':7687")\
  .option("authentication.basic.username", "some-uname'")\
  .option("authentication.basic.password", "some-pass")\
  .option("pushdown.columns.enabled", "false")\
  .option("relationship", "ACTED_IN")\
  .option("relationship.source.labels", "Person")\
  .option("relationship.target.labels", "Movie")\
  .load()
```

And it works for me too:
![Screenshot 2021-07-14 at 19 47 03](https://user-images.githubusercontent.com/1318539/125668584-55c109db-6b30-4dbc-a40b-37c746cc2bdf.png)

So I guess you're doing something else to get that error, but I can't see the code.


For the select issue you have to select it like 
```
dfr.select("`<rel.id>`")
```

![Screenshot 2021-07-14 at 19 47 07](https://user-images.githubusercontent.com/1318539/125668662-e24ac83a-93d4-4ff2-a489-8f9a73f511ad.png)

**Comment by RGEv1L** [comment]
yeah, it works with this approach. Thanks a lot.
But what about the error?

**Comment by RGEv1L** [comment]
I am fetching relationships using the custom query in spark and it seems to work fine and the labels are also working fine. It's just the connectors seems to not work with relationship field.

**Comment by utnaf** [comment]
Can you please give me the code that causes the error?

**Comment by RGEv1L** [comment]
when i decleare the dfr.. using neo4j connector like this, it suddenly throws error.
v = spark.read.format("org.neo4j.spark.DataSource")\
...     .option("url", "bolt://3.137.143.193:7687")\
...     .option("authentication.basic.username", "neo4j")\
...     .option("authentication.basic.password", "2aca4d3e-fa5b-4f4a-8974-c2adf32e3620")\
...   .option("pushdown.columns.enabled", "false")\
...   .option("relationship", "ACTED_IN")\
...   .option("relationship.source.labels", "Person")\
...   .option("relationship.target.labels", "Movie")\
...   .load()
21/07/15 20:23:28 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: For the following exception
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.service.SchemaService.retrieveSchemaFromApoc(SchemaService.scala:68)
	at org.neo4j.spark.service.SchemaService.liftedTree2$1(SchemaService.scala:171)
	at org.neo4j.spark.service.SchemaService.structForRelationship(SchemaService.scala:155)
	at org.neo4j.spark.service.SchemaService.struct(SchemaService.scala:262)
	at org.neo4j.spark.DataSource.$anonfun$inferSchema$1(DataSource.scala:41)
	at org.neo4j.spark.DataSource.callSchemaService(DataSource.scala:29)
	at org.neo4j.spark.DataSource.inferSchema(DataSource.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RGEv1L** [comment]
exactly when i declare the dfr and hit load() at the end of the declaration, I see this error.

```python
dfr = spark.read.format("org.neo4j.spark.DataSource")\
  .option("url", "bolt://'some-url':7687")\
  .option("authentication.basic.username", "some-uname'")\
  .option("authentication.basic.password", "some-pass")\
  .option("relationship", "ACTED_IN")\
  .option("relationship.source.labels", "Person")\
  .option("relationship.target.labels", "Movie")\
  .load()
21/07/15 20:23:28 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:23:30 WARN SchemaService: For the following exception
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.service.SchemaService.retrieveSchemaFromApoc(SchemaService.scala:68)
	at org.neo4j.spark.service.SchemaService.liftedTree2$1(SchemaService.scala:171)
	at org.neo4j.spark.service.SchemaService.structForRelationship(SchemaService.scala:155)
	at org.neo4j.spark.service.SchemaService.struct(SchemaService.scala:262)
	at org.neo4j.spark.DataSource.$anonfun$inferSchema$1(DataSource.scala:41)
	at org.neo4j.spark.DataSource.callSchemaService(DataSource.scala:29)
	at org.neo4j.spark.DataSource.inferSchema(DataSource.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RGEv1L** [comment]
complete code:
```
#in shell to invoke pyspark
pyspark --jars /home/akhan/PySpark/spark-3.0.3-bin-hadoop3.2/added_jars/neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar,/home/akhan/PySpark/spark-3.0.3-bin-hadoop3.2/added_jars/graphframes-0.8.0-spark3.0-s_2.12.jar --driver-memory 4g --executor-memory 4g

#in pyspark
spark.sparkContext.addPyFile('/home/akhan/PySpark/spark-3.0.3-bin-hadoop3.2/added_jars/neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar')
spark.sparkContext.addPyFile('/home/akhan/PySpark/spark-3.0.3-bin-hadoop3.2/added_jars/graphframes-0.8.0-spark3.0-s_2.12.jar')
from graphframes import *

from pyspark.sql import SparkSession
from pyspark.sql.functions import col,count
from pyspark.sql.types import StringType

dfr = spark.read.format("org.neo4j.spark.DataSource")
.option("url", "bolt://'some-url':7687")
.option("authentication.basic.username", "some-uname'")
.option("authentication.basic.password", "some-pass")
.option("relationship", "ACTED_IN")
.option("relationship.source.labels", "Person")
.option("relationship.target.labels", "Movie")
.load()
21/07/15 20:27:29 WARN SchemaService: Switching to query schema resolution
21/07/15 20:27:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:27:30 WARN SchemaService: Switching to query schema resolution
21/07/15 20:27:30 WARN SchemaService: For the following exception
org.neo4j.driver.exceptions.ClientException: Unable to convert scala.collection.immutable.Map$Map1 to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.service.SchemaService.retrieveSchemaFromApoc(SchemaService.scala:68)
	at org.neo4j.spark.service.SchemaService.liftedTree2$1(SchemaService.scala:171)
	at org.neo4j.spark.service.SchemaService.structForRelationship(SchemaService.scala:155)
	at org.neo4j.spark.service.SchemaService.struct(SchemaService.scala:262)
	at org.neo4j.spark.DataSource.$anonfun$inferSchema$1(DataSource.scala:41)
	at org.neo4j.spark.DataSource.callSchemaService(DataSource.scala:29)
	at org.neo4j.spark.DataSource.inferSchema(DataSource.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by utnaf** [comment]
> 
> dfr.show()
> 
> ```
> +--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
> |<rel.id>|<rel.type>|<source.id>|<source.labels>|       source.name|source.born|<target.id>|<target.labels>|        target.title|      target.tagline|target.released|           rel.roles|
> +--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
> |       7|  ACTED_IN|          8|       [Person]|       Emil Eifrem|       1978|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|              [Emil]|
> |       3|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|       [Agent Smith]|
> |       2|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|          [Morpheus]|
> |       1|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|           [Trinity]|
> |       0|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|          0|        [Movie]|          The Matrix|Welcome to the Re...|           1999|               [Neo]|
> |      11|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|       [Agent Smith]|
> |      10|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|          [Morpheus]|
> |       9|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|           [Trinity]|
> |       8|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|          9|        [Movie]| The Matrix Reloaded|      Free your mind|           2003|               [Neo]|
> |      18|  ACTED_IN|          4|       [Person]|      Hugo Weaving|       1960|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|       [Agent Smith]|
> |      17|  ACTED_IN|          3|       [Person]|Laurence Fishburne|       1961|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|          [Morpheus]|
> |      16|  ACTED_IN|          2|       [Person]|  Carrie-Anne Moss|       1967|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|           [Trinity]|
> |      15|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|         10|        [Movie]|The Matrix Revolu...|Everything that h...|           2003|               [Neo]|
> |      24|  ACTED_IN|         13|       [Person]|         Al Pacino|       1940|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|       [John Milton]|
> |      23|  ACTED_IN|         12|       [Person]|   Charlize Theron|       1975|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|    [Mary Ann Lomax]|
> |      22|  ACTED_IN|          1|       [Person]|      Keanu Reeves|       1964|         11|        [Movie]|The Devil's Advocate|Evil has its winn...|           1997|       [Kevin Lomax]|
> |      35|  ACTED_IN|         25|       [Person]|    James Marshall|       1967|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|[Pfc. Louden Downey]|
> |      33|  ACTED_IN|         23|       [Person]|      Kevin Pollak|       1957|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|  [Lt. Sam Weinberg]|
> |      34|  ACTED_IN|         24|       [Person]|        J.T. Walsh|       1943|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|[Lt. Col. Matthew...|
> |      37|  ACTED_IN|         28|       [Person]|      Aaron Sorkin|       1961|         15|        [Movie]|      A Few Good Men|In the heart of t...|           1992|        [Man in Bar]|
> +--------+----------+-----------+---------------+------------------+-----------+-----------+---------------+--------------------+--------------------+---------------+--------------------+
> only showing top 20 rows
> ```
> 

I see here in your second comment that you still able to invoke `dfr.show()` and to print the content, is it still the case?

**Comment by RGEv1L** [comment]
yup.

**Comment by RGEv1L** [comment]
```python
e = spark.read.format("org.neo4j.spark.DataSource")\
  .option("query", "MATCH (n:Person)-[m:ACTED_IN]->(o:Movie) RETURN id(n) as src,id(o) as dst,type(m) AS relationship ")\
  .option("partitions", "5")\
  .load()
```

although i am able to load labels  properly using default method, and I am using custom queries like above currently, but it gives error only when fetching using relationships

**Comment by RGEv1L** [comment]
at a point, it gave me this error as well about too many labels `apoc.meta.stats`

**Comment by utnaf** [comment]
> yup.

Then I'm pretty sure that a non-error, or a bad log... would you mind trying again using this JAR?

[neo4j-connector-apache-spark_2.12-4.0.2_for_spark_3.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/6824525/neo4j-connector-apache-spark_2.12-4.0.2_for_spark_3.jar.zip)

**Comment by RGEv1L** [comment]
@utnaf 
I have used 4.0.0, 4.0.1 and 4.0.2 , but non of them seems to fix the issue!

**Comment by utnaf** [comment]
It's not an issue, if you can keep using the dataframe (ie: you can do `dfr.show()` and it shows the content). It's just a bad log, I'll try to fix it later this week.

**Comment by utnaf** [comment]
Please try the latest pre-release that came out last friday https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.3-pre

**Comment by conker84** [comment]
@RGEv1L any feedback on this?

**Comment by conker84** [comment]
I'm closing this for lack of feedback, feel free to reopen in case you have new info
