### ISSUE TITLE
Neo4j cannot write to buffer with heavy spark jobs

### ISSUE THREAD

**Issue by antoniomaccioni** [neo4j-contrib/neo4j-spark-connector#43]
Hi,
when I use the connector with relatively small graphs everything works great. When I used it with a larger graph (25 M nodes, 80M edges), the spark jobs get stucked. No errors but do not proceed in their execution. 
I run algorithms such as pageRank and the executions stops at the first submitted stage, probably during a reading phase from neo4j.
I then realized that after a while few errors appear on the neo4j side. 
On the _debug.log_:

 `2017-08-15 16:01:42.298+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to write response to driver Cannot write to buffer when closed
java.io.IOException: Cannot write to buffer when closed
	at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:163)
	at org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:94)
	at org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:427)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onSuccess(BoltResponseMessageWriter.java:76)
	at org.neo4j.bolt.v1.messaging.MessageProcessingHandler.onFinish(MessageProcessingHandler.java:111)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.after(BoltStateMachine.java:103)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:199)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:80)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:123)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:96)
	at java.lang.Thread.run(Thread.java:748)
`
that results in the following errors in the _neo4j.log_:

`2017-08-15 16:00:08.788+0000 ERROR Client triggered an unexpected error [UnknownError]: Cannot write to buffer when closed, reference 18ca61c4-b34b-45b7-b692-c353e4cb1eb1.
`

These errors seems to appear often with last versions of Neo4j but no solution was found yet or it was always related to something different than my case.
Any idea on what's going on?

**Comment by recurse-id** [comment]
Are there any updates to this issue?

**Comment by antoniomaccioni** [comment]
I did not solve the problem.

**Comment by jexp** [comment]
Are you batching those jobs?
You should make sure that the job is batched into say 100k updates at a time.

What is the exact code you're running?

**Comment by antoniomaccioni** [comment]
I do not think I was batching it.
Does the batching affect the correctness of the computation?

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
