### ISSUE TITLE
I got an exception,but I can't handle it

### ISSUE THREAD

**Issue by laosun1115** [neo4j-contrib/neo4j-spark-connector#430]
### Versions

- Spark:2.4
- Scala:2.11
- Neo4j:3.5.14
- Neo4j Connector:neo4j-spark-connector

When I use spark.dataframe to write data to neo4j,the application running for a long time not over,then i see the `debug.log`,it throws an exception

I've been looking online for a long time,but no solution was found,please help me,thank you
```
2022-05-07 09:11:41.567+0000 INFO [o.n.c.c.r.RaftReplicator] Replication attempt 1078 to leader MemberId{100be7da}: DistributedOperation{content=TransactionRepresentationReplicatedTransaction{tx=PhysicalTransactionRepresentation[masterId:-1,authorId:-1,timeStarted:1651831156861,latestCommittedTxWhenStarted:10664015,timeCommitted:1651850191237,lockSession:31,additionalHeader:[]commands.length:7002}, globalSession=GlobalSession{sessionId=d90dd626-6850-495b-9b92-e124df66b921, owner=MemberId{100be7da}}, operationId=LocalOperationId{localSessionId=12, sequenceNumber=13210}}
2022-05-07 09:11:42.870+0000 INFO [o.n.c.c.r.RaftReplicator] Replication attempt 1078 to leader MemberId{100be7da}: DistributedOperation{content=TransactionRepresentationReplicatedTransaction{tx=PhysicalTransactionRepresentation[masterId:-1,authorId:-1,timeStarted:1651831159946,latestCommittedTxWhenStarted:10664015,timeCommitted:1651850191238,lockSession:31,additionalHeader:[]commands.length:7002}, globalSession=GlobalSession{sessionId=d90dd626-6850-495b-9b92-e124df66b921, owner=MemberId{100be7da}}, operationId=LocalOperationId{localSessionId=8, sequenceNumber=40832}}
2022-05-07 09:11:46.562+0000 INFO [o.n.c.m.SenderService] Connected: [id: 0x34c7ec0d, L:/10.145.33.139:58186 - R:/10.145.33.139:17000]
2022-05-07 09:11:46.562+0000 INFO [o.n.c.p.h.HandshakeServerInitializer] Installing handshake server on channel [id: 0x4d088919, L:/10.145.33.139:17000 - R:/10.145.33.139:58186]
2022-05-07 09:11:46.562+0000 INFO [o.n.c.p.h.HandshakeClientInitializer] Initiating handshake on channel [id: 0x34c7ec0d, L:/10.145.33.139:58186 - R:/10.145.33.139:17000]
2022-05-07 09:11:46.562+0000 INFO [o.n.c.p.h.HandshakeServerInitializer] Handshake completed on channel [id: 0x4d088919, L:/10.145.33.139:17000 - R:/10.145.33.139:58186]. Installing: raft version:2
2022-05-07 09:11:46.562+0000 INFO [o.n.c.p.h.HandshakeClientInitializer] Handshake completed on channel [id: 0x34c7ec0d, L:/10.145.33.139:58186 - R:/10.145.33.139:17000]. Installing: raft version:2
2022-05-07 09:11:46.563+0000 ERROR [o.n.c.p.h.HandshakeServerInitializer] Exception in outbound for channel: [id: 0x4d088919, L:/10.145.33.139:17000 - R:/10.145.33.139:58186] failed to allocate 16777216 byte(s) of direct memory (used: 21458059271, max: 21474836480)
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 21458059271, max: 21474836480)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:726)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:681)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:122)
2022-05-07 09:11:46.563+0000 WARN [o.n.c.m.SenderService] Lost connection to: 10.145.33.139:17000 (/10.145.33.139:17000)
2022-05-07 09:11:46.563+0000 ERROR [o.n.c.p.h.HandshakeClientInitializer] Exception in outbound for channel: [id: 0x34c7ec0d, L:/10.145.33.139:58186 ! R:/10.145.33.139:17000] Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:328)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:979)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:241)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClientInitializer.onHandshakeComplete(HandshakeClientInitializer.java:136)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClientInitializer.lambda$initiateHandshake$3(HandshakeClientInitializer.java:115)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClient.handle(HandshakeClient.java:179)
	at org.neo4j.causalclustering.protocol.handshake.SwitchOverResponse.dispatch(SwitchOverResponse.java:23)
	at org.neo4j.causalclustering.protocol.handshake.NettyHandshakeClient.channelRead0(NettyHandshakeClient.java:23)
	at org.neo4j.causalclustering.protocol.handshake.NettyHandshakeClient.channelRead0(NettyHandshakeClient.java:11)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:122)
2022-05-07 09:11:46.564+0000 ERROR [o.n.c.p.h.HandshakeClientInitializer] Exception in outbound for channel: [id: 0x34c7ec0d, L:/10.145.33.139:58186 ! R:/10.145.33.139:17000]
java.nio.channels.ClosedChannelException
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:337)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:979)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:241)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClientInitializer.onHandshakeComplete(HandshakeClientInitializer.java:136)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClientInitializer.lambda$initiateHandshake$3(HandshakeClientInitializer.java:115)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.neo4j.causalclustering.protocol.handshake.HandshakeClient.handle(HandshakeClient.java:179)
	at org.neo4j.causalclustering.protocol.handshake.SwitchOverResponse.dispatch(SwitchOverResponse.java:23)
	at org.neo4j.causalclustering.protocol.handshake.NettyHandshakeClient.channelRead0(NettyHandshakeClient.java:23)
	at org.neo4j.causalclustering.protocol.handshake.NettyHandshakeClient.channelRead0(NettyHandshakeClient.java:11)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:122)
```

Here is the code I used
```
def createNodes(dataFrame: DataFrame, nodes: (String, Seq[String]), renamedColumns: Map[String, String] = Map.empty, batchsize: Int = 500,num:Int=10000, isMerge: Boolean = true)(implicit sc: SparkContext,ss:SparkSession) = {

  val nodeLabel: String = renamedColumns.getOrElse(nodes._2.head, nodes._2.head)
  Neo4jUtils.createUniqueIndex(ss,nodes._1,nodeLabel)
  if(nodes._1.contains("明细")) Neo4jUtils.createIndex(ss,nodes._1,"日期")
  val createStatement =
    s"""
      UNWIND {rows} as row
      ${if (isMerge) "MERGE" else "CREATE"} (node:`${nodes._1}` {`${nodeLabel}` : row.node_properties.`${nodeLabel}`})
      ON CREATE SET node += row.node_properties
      ON MATCH SET node += row.node_properties
      """
  println(createStatement)
  val partitions = Math.max(1, (dataFrame.count() / num).asInstanceOf[Int])
  val config = Neo4jConfig(sc.getConf)
  var count = 0
  dataFrame.distinct().persist().repartition(partitions).foreachPartition(rows => {
    rows.grouped(batchsize).foreach(rows => {
      val count_t = rows.map(r => r.get(1)).distinct.size
      val params: AnyRef = rows.map(r =>
        Map(
          "node_properties" -> nodes._2.map(c => (renamedColumns.getOrElse(c, c), r.getAs[AnyRef](c))).toMap.asJava)
          .asJava).asJava
      count = Neo4jDataFrame.execute(config, createStatement, Map("rows" -> params).asJava, write = true).counters().nodesCreated()
      if (count != count_t) {
        for (i <- 0 until 3; if count != 0) {
          count = Neo4jDataFrame.execute(config, createStatement, Map("rows" -> params).asJava, write = true).counters().nodesCreated()
        }
      }
    })
  })

} 

def execute(config: Neo4jConfig, query: String, parameters: java.util.Map[String, AnyRef], write: Boolean = false): ResultSummary = {
  val driver = config.driver()
  val session = driver.session()
  try {
    val runner = new TransactionWork[ResultSummary]() {
      override def execute(tx: Transaction): ResultSummary =
        tx.run(query, parameters).consume()
    }
    if (write) {
      //        val x1 = session.beginTransaction()
      //        val x2 = x1.run(query,parameters)
      //        x2.consume().counters().labelsAdded()
      //        x1.commitAsync()

      session.writeTransaction(runner)

    }
    else
      session.readTransaction(runner)
  }
    //    catch {
    //      case e:Exception=>null
    //    }
  finally {
    if (session.isOpen) session.close()
    driver.close()
  }
}
```

**Comment by conker84** [comment]
Hi @laosun1115 you're using a deprecated version of the spark connector, please migrate to the new one.
You can take a look to the documentation:
https://neo4j.com/docs/spark/current/
Cheers
Andrea
