### ISSUE TITLE
Neo4j Spark Connector not returning results

### ISSUE THREAD

**Issue by ysule** [neo4j-contrib/neo4j-spark-connector#48]
Hi Michael,
I have the following Scala script that i am running with Spark and Below it is the Code I tried in the REPL
In both cases I get the same error which I have attached.

	import org.neo4j.spark._
	import org.apache.spark.{SparkConf,SparkContext}
	import org.apache.spark.rdd._
	object neo4jRead
	{
	  def main(args: Array[String]): Unit = {
	    val conf = new SparkConf().setAppName("NeoRead")
	      .set("spark.ui.enabled","false")
	      .set("spark.neo4j.bolt.url","bolt://127.0.0.1:7687")
	      .set("spark.neo4j.bolt.user","neo4j")
	      .set("spark.neo4j.bolt.password","neo4j")

	    val sc = new SparkContext(conf)
	    val query: String = "MATCH (n:Person) RETURN n LIMIT 100"
	    val neo = Neo4j(sc)
	    val resultSet = neo.cypher(query).loadRowRdd
	    println(resultSet.take(10))
	  }
	}

I tried the following code in my Spark-Scala REPL

	import org.neo4j.spark._
	val neo = Neo4j(sc)
	val data = neo.cypher("MACH (n:Person) RETURN n LIMIT 100").loadRowRdd
	data.collect()

and this is the stack trace on the REPL.
==========================
java.io.NotSerializableException: org.neo4j.driver.internal.InternalNode
Serialization stack:
        - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<0>)
        - element of array (index: 0)
        - array (class [Ljava.lang.Object;, size 1)
        - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
        - object (class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema, [node<0>])
        - element of array (index: 0)
        - array (class [Lorg.apache.spark.sql.Row;, size 100)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/10/30 02:14:06 ERROR TaskSetManager: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: org.neo4j.driver.internal.InternalNode
Serialization stack:
        - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<0>)
        - element of array (index: 0)
        - array (class [Ljava.lang.Object;, size 1)
        - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
        - object (class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema, [node<0>])
        - element of array (index: 0)
        - array (class [Lorg.apache.spark.sql.Row;, size 100); not retrying
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: org.neo4j.driver.internal.InternalNode
Serialization stack:
        - object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<0>)
        - element of array (index: 0)
        - array (class [Ljava.lang.Object;, size 1)
        - field (class: org.apache.spark.sql.catalyst.expressions.GenericRow, name: values, type: class [Ljava.lang.Object;)
        - object (class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema, [node<0>])
        - element of array (index: 0)
        - array (class [Lorg.apache.spark.sql.Row;, size 100)
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1890)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1903)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1916)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1930)
  at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
  ... 50 elided

I changed the Node Label in the query. 
Please suggest an alternative.

**Comment by ysule** [comment]
I have a HDP 2.5 cluster with Spark 2.0.0 intalled. I am using the appropriate JAR for the code.

**Comment by jexp** [comment]
You cannot return neo4j Bolt driver nodes as they are not serializable.

You can return `id(n)` or `properties(n)` (which is a map). 

Please let me know if it works.

**Comment by ysule** [comment]
@jexp I rectified my mistake a day before. My analysis revealed the same thing which you said. I'll be closing this issue now. 
Thanks for the reply.

**Comment by vishwasjione** [comment]
Could you please help me with how do you see content of "data" below 

val data = neo.cypher("MACH (n:Person) RETURN n LIMIT 100").loadRowRdd
