### ISSUE TITLE
Spark runs with connector for a while then looses connection to neo4j...thread error

### ISSUE THREAD

**Issue by codejoy** [neo4j-contrib/neo4j-spark-connector#51]
I was running my code with this connector, it runs fine on small data sets when I let it rip on the full data set.  It errors out with these error (from log):
```

2017-10-13 01:17:45.073+0000 ERROR [o.n.b.t.SocketTransportHandler] Fatal error occurred when handling a client connection: unable to create new native thread unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at org.neo4j.kernel.impl.util.Neo4jJobScheduler.schedule(Neo4jJobScheduler.java:94)
    at org.neo4j.bolt.v1.runtime.concurrent.ThreadedWorkerFactory.newWorker(ThreadedWorkerFactory.java:68)
    at org.neo4j.bolt.v1.runtime.MonitoredWorkerFactory.newWorker(MonitoredWorkerFactory.java:54)
    at org.neo4j.bolt.BoltKernelExtension.lambda$newVersions$1(BoltKernelExtension.java:234)
    at org.neo4j.bolt.transport.ProtocolChooser.handleVersionHandshakeChunk(ProtocolChooser.java:95)
    at org.neo4j.bolt.transport.SocketTransportHandler.chooseProtocolVersion(SocketTransportHandler.java:109)
    at org.neo4j.bolt.transport.SocketTransportHandler.channelRead(SocketTransportHandler.java:58)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
    at io.netty.channel.AbstractChannelHandlerContext.invokeC
```

Error that pops up during execution from spark-submit:

```
org.neo4j.driver.v1.exceptions.ClientException: Failed to establish connection with server. Make sure that you have a server with bolt enabled on localhost:7687
    at org.neo4j.driver.internal.connector.socket.SocketClient.negotiateProtocol(SocketClient.java:197)
    at org.neo4j.driver.internal.connector.socket.SocketClient.start(SocketClient.java:76)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.<init>(SocketConnection.java:63)
    at org.neo4j.driver.internal.connector.socket.SocketConnector.connect(SocketConnector.java:52)
    at org.neo4j.driver.internal.pool.InternalConnectionPool.acquire(InternalConnectionPool.java:113)
    at org.neo4j.driver.internal.InternalDriver.session(InternalDriver.java:53)
   
```

Though I thought I have the settings on my machine right:

Updated the neo4j-community.vmoptions:

-server
-Xms4096m
-Xmx4096m
-XX:NewSize=1024m

C02RH2U9G8WM:~ meuser$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

I do checks when it is running and never go over 300 threads.  I am so lost as to why this is breaking.   Posting here hoping there is something I missed someone has an idea for me to look at.

**Comment by jexp** [comment]
Hi thanks a lot for the report,

What kind of query are you running?
Is there any easy way to reproduce this?

The `open files (-n) 256` looks super low.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
