### ISSUE TITLE
Project build fails after SBT upgrade to 1.9.0, but works for 1.8.3

### ISSUE THREAD

**Issue by oleksii-suprun** [neo4j-contrib/neo4j-spark-connector#516]
## Expected Behavior (Mandatory)
Project compiles

## Actual Behavior (Mandatory)
SBT fails with the exception.
```
[info] Fetching artifacts of
[info] Fetched artifacts of
[error] java.net.URISyntaxException: Illegal character in path at index 123: https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.12/5.0.0_for_spark_3/neo4j-connector-apache-spark_${scala.binary.version}-5.0.0_for_spark_3.jar
[error]         at java.net.URI$Parser.fail(URI.java:2847)
[error]         at java.net.URI$Parser.checkChars(URI.java:3020)
[error]         at java.net.URI$Parser.parseHierarchical(URI.java:3104)
[error]         at java.net.URI$Parser.parse(URI.java:3052)
[error]         at java.net.URI.<init>(URI.java:588)
[error]         at java.net.URL.toURI(URL.java:989)
[error]         at sjsonnew.JavaExtraFormats.$anonfun$urlStringIso$1(JavaExtraFormats.scala:40)
[error]         at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[error]         at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[error]         at sjsonnew.StandardFormats$OptionFormat.write(StandardFormats.scala:37)
[error]         at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:44)
[error]         at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:33)
[error]         at sjsonnew.Builder.addField(Builder.scala:43)
[error]         at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:36)
[error]         at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:9)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error]         at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error]         at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error]         at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error]         at sjsonnew.Builder.addField(Builder.scala:43)
[error]         at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:42)
[error]         at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:9)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error]         at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error]         at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error]         at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error]         at sjsonnew.Builder.addField(Builder.scala:43)
[error]         at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:26)
[error]         at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:9)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error]         at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error]         at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error]         at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error]         at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error]         at sjsonnew.Builder.addField(Builder.scala:43)
[error]         at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:27)
[error]         at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:9)
[error]         at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[error]         at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:20)
[error]         at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[error]         at sjsonnew.SupportConverter.$anonfun$toJson$1(SupportConverter.scala:14)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at sjsonnew.SupportConverter.toJson(SupportConverter.scala:14)
[error]         at sjsonnew.SupportConverter.toJson$(SupportConverter.scala:13)
[error]         at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[error]         at sbt.util.FileOutput.write(Output.scala:38)
[error]         at sbt.util.FileBasedStore.write(CacheStore.scala:89)
[error]         at sbt.internal.InMemoryCacheStore$CacheStoreImpl.write(InMemoryCacheStore.scala:75)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] (update) java.net.URISyntaxException: Illegal character in path at index 123: https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.12/5.0.0_for_spark_3/neo4j-connector-apache-spark_${scala.binary.version}-5.0.0_for_spark_3.jar
[error] Total time: 4 s, completed Jun 7, 2023 1:03:17 PM

```

## How to Reproduce the Problem
Update SBT to version `1.9.0` and try to compile the project using `neo4j-connector-apache-spark` as a dependency:
```
sbt clean compile
```

### Simple Dataset (where it's possible)
N/A

### Steps (Mandatory)
1. Create an SBT project
1. Add `libraryDependencies += "org.neo4j" %% "neo4j-connector-apache-spark" % "5.0.0_for_spark_3"`
1. Run SBT build

## Screenshots (where it's possible)
N/A

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: 3.3.2
- Scala: 2.12.15
- Neo4j:
- Neo4j Connector: 5.0.0_for_spark_3

## Additional information
N/A

**Comment by fbiville** [comment]
Thanks for the report, I can indeed reproduce it.
I wonder if this has to do with non-constant `artifactId` that Maven complains about when building:
```
[WARNING] 'artifactId' contains an expression but should be a constant. @ org.neo4j:neo4j-connector-apache-spark_${scala.binary.version}:${parent.version}_for_spark_3, /Users/fbiville/workspace/neo4j-spark-connector/spark-3/pom.xml, line 7, column 17
```

The [released POM for 5.0.0](https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.12/5.0.0_for_spark_3/neo4j-connector-apache-spark_2.12-5.0.0_for_spark_3.pom) looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>neo4j-connector-apache-spark_${scala.binary.version}</artifactId>
    <name>neo4j-connector-apache-spark-${spark.version}</name>
    <description>Spark ${spark.version} for Neo4j Connector for Apache Spark using the binary Bolt Driver</description>

    <version>${parent.version}_for_spark_3</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-connector-apache-spark_2.12</artifactId>
        <version>5.0.0</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-connector-apache-spark_${scala.binary.version}_common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-connector-apache-spark_${scala.binary.version}_test-support</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

I assume that's the first resource SBT fetches to resolve the main artifact and its dependencies, so we need to figure out a way to fix the interpolation.
