### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by gchokeen** [neo4j-contrib/neo4j-spark-connector#64]
Hey,

I was trying to do a simple read option in the neo4j using spark. But I am getting the following error "NoSuchMethodError". Any idea about this issue?

First I tried with
> libraryDependencies += "neo4j-contrib" % "neo4j-spark-connector" % "2.1.0-M4"
Then
> libraryDependencies += "neo4j-contrib" % "neo4j-spark-connector" % "2.2.1-M5"

In both case I am getting the same error

## QUERY
 ```
val neo = Neo4j(sc)
  val df = neo.cypher("MATCH (n:Person) RETURN n.name").partitions(5).batch(100).loadRowRdd
  print(df.count)
```

## SYSTEM DETAILS

 - Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151)
 - SPARK 2.3.1

`
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at org.neo4j.spark.Neo4jPartition.<init>(Neo4jPartition.scala:12)
	at org.neo4j.spark.Neo4jRDD$$anonfun$getPartitions$1.apply(Neo4j.scala:457)
	at org.neo4j.spark.Neo4jRDD$$anonfun$getPartitions$1.apply(Neo4j.scala:457)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.neo4j.spark.Neo4jRDD.getPartitions(Neo4j.scala:457)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1958)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1157)
	at ReadParquet.writeTagsNeo4j$.main(write-neo4j.scala:45)
	at ReadParquet.writeTagsNeo4j.main(write-neo4j.scala)`

**Comment by gchokeen** [comment]
@jexp : Thanks for your thoughts, I fixed that issue by updating the scala version sbt

```
scalaVersion := "2.10.4"
to 
scalaVersion := "2.11.8"
```

But now I am getting handshaking error!
```

org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Failed to establish connection with the server
	at org.neo4j.driver.internal.async.HandshakeHandler.transformError(HandshakeHandler.java:178)
	at org.neo4j.driver.internal.async.HandshakeHandler.exceptionCaught(HandshakeHandler.java:99)
```

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
