### ISSUE TITLE
Connector can't handle array type

### ISSUE THREAD

**Issue by swayam18** [neo4j-contrib/neo4j-spark-connector#70]
I am trying to load an object that has an array property into a dataset. I have defined a custom case class to represent the data:

`case class MediaNode(id: String, urls: Array[String])`

This is what the query looks like:
```
MATCH (m:Media)
RETURN m.id as id, m.urls as urls
```

But, upon executing the query via `neo.cypher(query).loadDataframe.as[Media]`, the executor blows up with the following error:

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: need an array field but got string;
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveDeserializer$$anonfun$apply$33$$anonfun$applyOrElse$13$$anonfun$11.applyOrElse(Analyzer.scala:2317)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveDeserializer$$anonfun$apply$33$$anonfun$applyOrElse$13$$anonfun$11.applyOrElse(Analyzer.scala:2307)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
...
```

Someone else seems to have the same problem: https://stackoverflow.com/questions/46314869/spark-neo4j-throws-error-runtimeexception-java-util-collectionsunmodifiablera#

I tried changing `MediaNode#urls` to a `String` and parsing the string myself but that doesn't work either.

Current workaround is to `UNWIND` and then collect in the dataframe, but if there are many items in the url it will get expensive to do so.

**Comment by jexp** [comment]
Could you try this build and see if that works: https://www.dropbox.com/s/rbjio9xhggm2a0f/neo4j-spark-connector-2.2.1-M5.jar?dl=0

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
