### ISSUE TITLE
How to get only matched dataframes

### ISSUE THREAD

**Issue by gchokeen** [neo4j-contrib/neo4j-spark-connector#72]
I have spark sql datafram with column name bigrams and I have some Terms in the neo4j with Term weight data. So I want match all the bigrams data against neo4j Terms node and need to get all the Matched result as new dataframe.

My DataFrame look like this

```
+------------------+
|bigrams           |
+------------------+
|have you          |
|you got           |
|got what          |
|what it           |
|it takes          |
|takes to          |
|to be             |
|be a              |
|a growth          |
|growth hacker     |

```

So I write some code like this, but unfortunately I am getting exception "**SparkException: Task not serializable**"

```

val query = "MATCH (n:Term) WHERE  n.term = {term} RETURN n";

    val results = bigramsDf.foreachPartition { row =>
       val neo = Neo4j(sc).cypher(query)
      row.toSeq.foreach{term => {
           neo.param("term", Seq(term)).batch(25).loadDataFrame
      }}
 }
```

**Comment by jexp** [comment]
Is there more to the exception.

You also have to provide partitions to your batch()

**Comment by gchokeen** [comment]
Yes I added partitions 

`neo.param("term", Seq(term)).partitions(5).batch(25).loadDataFrame
`
This is the full exception
`
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2094)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:924)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:923)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:923)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply$mcV$sp(Dataset.scala:2305)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2305)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2305)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2304)
	at ReadParquet.NGRAM$.main(NGRAM.scala:105)
	at ReadParquet.NGRAM.main(NGRAM.scala)
Caused by: java.io.NotSerializableException: org.apache.spark.SparkContext
Serialization stack:
	- object not serializable (class: org.apache.spark.SparkContext, value: org.apache.spark.SparkContext@6b9a1205)
	- field (class: ReadParquet.NGRAM$$anonfun$5, name: sc$1, type: class org.apache.spark.SparkContext)
	- object (class ReadParquet.NGRAM$$anonfun$5, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
`

**Comment by jexp** [comment]
Can you try instead of using spark-context (which should also actually be available inside of the task)

To use sparkconfig? which is serializable.

**Comment by gchokeen** [comment]
Ok I used **SparkContext.getOrCreate()** inside map function and it worked, but I am getting empty outputs, I also not able to convert it as Dataframe, Do you have any idea?

> ()
> ()
> ()
> 

  ```
  val query = "MATCH (n:Term) where n.term = {term} RETURN n.term,n.count  ";

    val nRdd = rdd.map { term =>
      val neo = Neo4j(SparkContext.getOrCreate()).cypher(query)

      val resultRDD = neo.param("term", Seq(term)).loadRowRdd

    }

  nRdd.take(20).foreach(println)
```

**Comment by gchokeen** [comment]
Hi @jexp I almost done, I need one final push

The above method still not working for me so, I tried to convert it as single query as like below , its definitely working when I pass params as direct string, but when I stored that string in variable and if I used in query, I am getting blank results, Can you tell me how to fix that?

`WITH ['our own', 'own spin', 'spin on', 'on growth', 'growth hacking'] as terms MATCH (t:Term) where t.term in terms RETURN t.term as term,t.count as tf`


```
val queryParams = 'our own', 'own spin', 'spin on', 'on growth', 'growth hacking';

val query = "WITH [ {terms} ] as terms MATCH (t:Term) where t.term in terms RETURN t.term as term,t.count as tf  ";
    val neo = Neo4j(sc)
     val nRdd =neo.cypher(query).param("terms",queryParams).loadDataFrame("term" -> "string","tf" -> "long");

  nRdd.show(false) 
```

**Comment by jexp** [comment]
perhaps it's the wrong type of list?
Try to create a Scala or Java list (e.g. `Arrays.asList()`) directly.
Also your syntax is wrong, it has to be `WITH {terms} as terms`
Or easier: `MATCH (t:Term) where t.term in {terms}`

**Comment by jexp** [comment]
Sorry for the slow progress, but my spark-fu is weak :)

**Comment by jexp** [comment]
Please share your final statement so we can add it to the docs as an example.

**Comment by gchokeen** [comment]
Hi @jexp , Thanks for trying to help me, I finally got results in following way.

```
    val neo = Neo4j(sc)

 val queryParams = bigramsDf.collect().map(_.getString(0)).mkString("\"", "\", \"", "\"")

    val query = "MATCH (t:Term) where t.term in [ " + queryParams + " ] RETURN t.term as term,t.count as tf  ";
    val bigramTerms =neo.cypher(query).loadDataFrame("term" -> "string","tf" -> "long");
```

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
